### ISSUE TITLE
Possible re-license to MIT/Apache2?

### ISSUE THREAD

**Issue by steveklabnik** [dragostis/pest#96]
Hey @dragostis !

In short, `pest` is a dependency of `mdBook`, and we'd like to include `mdBook` into the rust tree. There's some concern about MPL'd code, though, of which both `mdBook` and `pest` are. The discussion is here: https://internals.rust-lang.org/t/licenses-of-vendored-tools-in-the-rust-repo/4758

One possible solution would be to re-license pest, though, as the post says, this may not actually be necessary. I mostly wanted to open this issue to make you aware of the discussion, and to see how you felt about it.

**Comment by dragostis** [comment]
Since `pest` is a dependency, I don't have a very strong feeling about keeping the MPL licence. My main motivation behind this was the fact that MPL is itself a very permissive licence.

I'm still working on `v1.0` right now which might be a good time and place to make this change. The dependency on `pest` from `mdBook` stems from its use of `handlebars` which is not yet using the last version of `pest`, but whose author may be interested in upgrading to `v1.0` after I manage to land it.

**Comment by steveklabnik** [comment]
This issue is now moot from our side, so I'm going to give this a close! Thanks for the discussion here, I'm glad it was non-confrontational, I was a little worried. Licensing is tough. ❤️

**Comment by dragostis** [comment]
Thanks for letting me know. I see that pest was whitelisted which is probably a good solution for now. I'll still weigh in everything before launching 1.0.

**Comment by raviqqe** [comment]
I'm currently thinking about nom vs pest for my project. My parser is not going to be so complex, so both will be OK but only concern is the licensing. I hope relicensing under MIT/Apache in the near future so that developers using Rust easy to choose and integrate the library into other OSS and even commercial products. Of course, if you don't have any problem with that.

**Comment by dragostis** [comment]
@raviqqe The MPL 2.0 license does not stop you from incorporating the work in commercial products, it merely offers an incentive for everyone using the work to make any modifications made to it public, modifications which might as well land in a future version of pest.

**Comment by bd82** [comment]
> The MPL 2.0 license does not stop you from incorporating the work in commercial products, it merely offers an incentive for everyone using the work to make any modifications made to it public, modifications which might as well land in a future version of pest.

I'm afraid this a little naive.

The additional requirements of the partially copyleft properties of the license
may cause hurdles in more bureaucratic organizations, or "headaches" for developers who just want to use your software.

It would probably be easier to integrate pest into "corporate development" 
If it was available under a more permissive license such as MIT/Apache.
Even if in actuality the MPL is permissive enough.

**Comment by dragostis** [comment]
> I'm afraid this a little naive.

Surely. I guess the important question here would be whether changing to MIT/Apache would—by enabling companies to use the software—encourage open source contribution to the project. If this hypothesis holds in most cases, I see no reason not to re-license.

**Comment by dragostis** [comment]
I've changed the license to MIT.
